version = 0.1

[default.deploy.parameters]
stack_name = "serverless-app-ready-m2"
resolve_s3 = true
s3_prefix = "serverless-app-ready-m2"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
disable_rollback = true
image_repositories = []
parameter_overrides = "UserPool=users-stack-UserPool"