AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Module 3 start state

Resources:
  users:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./users/template.yaml
      Parameters:
        ParentStackName: !Ref AWS::StackName
        
  orders:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./orders/template.yaml
      Parameters:
        ParentStackName: !Ref AWS::StackName
        
Outputs:
  users:
    Description: Users API
    Value: !GetAtt users.Outputs.APIEndpoint
  orders:
    Description: Orders API
    Value: !GetAtt orders.Outputs.OrdersServiceEndpoint
