version = 0.1

[default.deploy.parameters]
stack_name = "user-profile-stack"
resolve_s3 = true
s3_prefix = "user-profile"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "UserPool=\"eu-central-1_LjfEtEoxt\""
image_repositories = []
